name: basic
work_dir: ./output
tb_dir: None
local_rank: -1

model:
  _type: UNet
  in_channels: 3
  out_channels: 3

optimizer:
  _type: Adam
  lr: 1e-4

loss:
  perceptual:
    layers:
      conv1_2: 0.384615 # 1 / 2.6
      conv2_2: 0.208333 # 1 / 4.8
      conv3_2: 0.270270 # 1 / 3.7
      conv4_2: 0.178571 # 1 / 5.6
      conv5_2: 6.666666 # 10 / 1.5
    criterion: L1
  weight:
    l1: 1

log:
  evaluate:
    interval_epoch: 1
  checkpoint:
    interval_epoch: 2
  tensorboard:
    scalar_interval: 100
    image_interval: 2000

train:
  num_epoch: 50
  dataset:
    folders: ./dataset
    transform:
      - ToTensor
      - Resize:
          size: 512
  dataloader:
    batch_size: 2
    num_workers: 2
    shuffle: True
  
evaluate:
  dataset:
    folders: ./dataset
    transform:
      - ToTensor
      - Resize:
          size: 512
  dataloader:
    batch_size: 1
    num_workers: 1
  
generate:
  dataset:
    folders: ./dataset
    transform:
      - ToTensor
      - Resize:
          size: 512
  dataloader:
    batch_size: 1
    num_workers: 1
  